Repository BHoM/File_Toolkit, pull requests merged in 2024-01, with the labels that each got.

#177 Update readme link
  README.md
Labels: type:documentation

#178 File_Adapter: filter File.Contents that are not Reference Type parameters; null checks
  File_Adapter/CRUD/Create/CreateJson.cs
  File_oM/Config/PushConfig.cs
Labels: type:feature

#180 Switch out for aggregating instead of array manipulation
  File_Adapter/CRUD/Create/CreateJson.cs
Labels: type:compliance

#181 Replace \\ in description attributes with /
  File_Engine/Compute/CreateFolders.cs
  File_Engine/Modify/RelativiseUserPath.cs
Labels: type:compliance
